[package]
name = "mpris_dbus_connector"
version = "0.1.0"
authors = ["fazekmar <fazekmar@gmail.com>"]
edition = "2018"

[profile.release]
lto = true

[dependencies]
dbus = "0.8.4"
byteorder = "1.3.4"
serde_json = "1.0.57"